name: Tests

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  install_and_test:
    defaults:
      run:
        shell: bash -l {0}

    strategy:
      fail-fast: false
      matrix:
        os:
          - label: Linux
            runner: ubuntu-latest

    name: Install And Test - ${{ matrix.os.label }}
    runs-on: ${{ matrix.os.runner }}
    steps:
      # Typical github repo checkout step.
      - name: Github Repo Checkout
        uses: actions/checkout@v3

      # Install Python on the runner.
      - name: Provision with Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      # Set the conda environment up using Mamba and install dependencies
      - name: Setup Environment
        uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: .github/lock_package.lock
          environment-name: DSWx-SAR

      # Install the S1-Reader OPERA-ADT project.
      
      - name: Install OpenCV
        run: python -m pip install opencv-python-headless

      - name: Install Project
        run: python -m pip install .

      # Test the project.
      - name: Test Project
        run: |
          pytest -vrpP
  